- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  include_tasks:
    - tasks/users.yml
    - tasks/cron.yml
    - tasks/packages.yml
